apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-01-01T01:23:45Y"
  labels:
    kubernetes.io/metadata.name: wenesday
  name: wenesday
  resourceVersion: "195"
  uid: 3803119b-738f-4a93-81a0-f57346407382
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
